Budget Assist App
paulshaun-kdtk/Budget-Assist pull request #3
Opened 2023-12-21 18:37 UTC by paulshaun-kdtk

# Changes
- added index (categories) page
- added devise for authentication
- added splash screen
- user can create, read and update groups and transactions
- link to previous PR: https://github.com/paulshaun-kdtk/Budget-Assist/pull/2

2023-12-21 19:01 UTC, julie-ify commented on README.md
> +**Live-Presentation** : https://www.loom.com/share/b12d950563214ce0a0ada22e760b77da?sid=bf358665-afbb-4a48-a3e3-f3f90ef54ca0
- [ ] Your video length should be 5 minutes maximum. Anything more than that violates the project requirement. Kindly record another video that fits within 5 minutes, and does not exceed this limit at all. We should be able to present our strongest points within a very short timeframe as this can prove decisive in our career.

- [ ] Kindly deploy your app and provide its link in the readme documentation. One reason for live demo applications is to help users, especially non-technical users (like recruiters) to be able to view the app without having to clone the repo. This can come in handy while making job applications.

2023-12-21 19:21 UTC, julie-ify commented on README.md
>  - [📖 Budget-App ](#Budget-App)
- [ ] Kindly style your splash screen to be similar to the design. There should be two buttons (not link tests) for login and sign up.

  ![image](https://github.com/paulshaun-kdtk/Budget-Assist/assets/81468675/e9468e65-54ef-4368-b770-0b034f0757ca)

  ![image](https://github.com/paulshaun-kdtk/Budget-Assist/assets/81468675/d40a7f76-0318-43c0-ba4f-86ea7fb787a7)

2023-12-21 19:24 UTC, julie-ify commented on README.md
>  - [📖 Budget-App ](#Budget-App)
- [ ] After signing up the user is redirected to this root path and they have to click the "Home" link to be taken to the users list page, which is not right. When a user signs up or logs in they should be automatically redirected to the categories list page, not the root path

  ![image](https://github.com/paulshaun-kdtk/Budget-Assist/assets/81468675/1db155b4-0ec3-4b3f-94c2-e971651ba8a7)

2023-12-21 19:31 UTC, julie-ify commented on app/views/users/index.html.erb
>    <div class="container-fluid">
- [ ] This `/users` page is not the page users should be taken to to view the categories. The categories page should be default page for users after logging in. They should be taken to the categories page, not `/users` page.

  The categories should be located in a route like this:  `/groups` or `/users/:user_id/groups`

- [ ] Kindly look at the design. You also need to fix your design. There is some kind of overflow that make the items not to fit the screen correctly.

- [ ] The "new category" button should be styled based on the design and placed at the bottom of the page.

- [ ] The categories should have the total amount of their transactions value displayed on them

  ![image](https://github.com/paulshaun-kdtk/Budget-Assist/assets/81468675/74403661-7b2d-483a-ac5d-a6693067bfa3)

  ![image](https://github.com/paulshaun-kdtk/Budget-Assist/assets/81468675/52bdec0d-a94c-4a1e-b998-fa29b7c25f3f)

2023-12-21 19:35 UTC, julie-ify commented on README.md
>  - [📖 Budget-App ](#Budget-App)
- [ ] The new transaction form page should have a back arrow button ("<") at the top bar for taking the users back to the transactions list page. Your page does not have that. Kindly add it.

  ![image](https://github.com/paulshaun-kdtk/Budget-Assist/assets/81468675/db2aa6a5-cd5c-4291-8769-8b8c356b775e)

2023-12-21 19:41 UTC, julie-ify commented on README.md
>  - [📖 Budget-App ](#Budget-App)
- [ ] The new category form page should have a back arrow button ("<") that leads the user to the categories list page.

  ![image](https://github.com/paulshaun-kdtk/Budget-Assist/assets/81468675/9d63045a-9289-40c1-8b20-b3228266e1e3)

  ![image](https://github.com/paulshaun-kdtk/Budget-Assist/assets/81468675/ac24a2d7-faef-400b-bab7-43bcf92d2616)

2023-12-21 19:43 UTC, julie-ify commented on README.md
>  - [📖 Budget-App ](#Budget-App)
- [ ] The new payment link should be a button and should be placed at the bottom of the page, like the design.

  ![image](https://github.com/paulshaun-kdtk/Budget-Assist/assets/81468675/4ff7563c-d505-4034-b07c-e23ffd667acd)

  ![image](https://github.com/paulshaun-kdtk/Budget-Assist/assets/81468675/76366054-3f3c-4610-9f08-9b2c7cc0f9b4)

2023-12-21 23:05 UTC, Reem-lab commented
Hello @paulshaun-kdtk could you check your slack?

2023-12-21 23:58 UTC, OyePriscilla requested changes
Hi @paulshaun-kdtk 👍 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Implemented `back `button ✔️ 
Displaye the amount of the total transaction in categories page ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-21 23:58 UTC, OyePriscilla commented on README.md
> +**Live-Presentation** : https://www.loom.com/share/b12d950563214ce0a0ada22e760b77da?sid=bf358665-afbb-4a48-a3e3-f3f90ef54ca0
- [ ] Please as suggested earlier by the previous reviewer, kindly ensure that your presentation does not exceeds 5mins, I think this will enhance your communication skills. 👍 

- [ ] Please add a live demo link of your project as suggested earlier. 👍

2023-12-21 23:58 UTC, OyePriscilla commented on app/views/splash/index.html.erb
> +            <% else %>
- [ ] Please kindly style your splash screen as we have it in the given template. 👍

2023-12-21 23:58 UTC, OyePriscilla commented on app/views/users/index.html.erb
> +                <th scope="col">total Amount</th>
- [ ] As raised earlier, kindly change the route naming from users to categories in order to follow the project requirement.

- [ ]  Kindly look at the design. You also need to fix your design. There is some kind of overflow that make the items not to fit the screen correctly.

- [ ]  The "new category" button should be styled **based on the design and placed at the bottom of the page**.

2023-12-21 23:58 UTC, OyePriscilla commented on app/controllers/payments_controller.rb
> +    @show_second_navbar = true
- [ ]  The new transaction form page should have a back arrow button ("<") at the top bar for taking the users back to the **transactions list page**. Your page does not have that. Kindly add it.

2023-12-23 21:48 UTC, rloterh commented on app/views/splash/index.html.erb
> +            <% else %>
well resolved! ✔️

2023-12-23 21:51 UTC, rloterh commented on README.md
> +**Live-Presentation** : https://www.loom.com/share/b12d950563214ce0a0ada22e760b77da?sid=bf358665-afbb-4a48-a3e3-f3f90ef54ca0
well resolved! ✔️

2023-12-23 21:57 UTC, rloterh commented on app/views/users/index.html.erb
> +                <th scope="col">total Amount</th>
needs improvement

2023-12-23 22:24 UTC, rloterh requested changes
Hi Shaun, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project, but you are almost there! 
🏁 🚦 🏃‍♂️   🌴 🏫 🌳 🏘️

## Highlights 👍  
🎲 Properly added required models, controllers, and corresponding views
🎲 Devise correctly implemented for authentication!
🎲 Schema follow given ERD!
🎲 App is running as intended!

## Required Changes ♻️
_Kindly check the comments under the review._

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-23 22:24 UTC, rloterh commented on app/views/users/index.html.erb
> +                <th scope="col">total Amount</th>
Your app is working well 👌 However, it will be a good idea if we can add a few tweaks to the design aspect so as to improve the look and feel. Please take note that it's one of the project's objectives that our design closely mimics the given [template design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=). Let's improve upon the design aspect by introducing the following tweaks:

- [ ] Let's ensure the _Add Category, Create Category, New Transaction, New Payment, Create Payment_ and all similar buttons conform to the specified typography, color (green with white rectangular inner border) and layout (is always sticky to the bottom of the screen) like can be seen in the template design.
- [ ] [OPTIONAL] Typography and the general layout of the app design should be similar to the original design.

**Your design:**
**Payment:**        |  **Your categories page:**        |  **Your transaction page**     
:-------------------------:|:-------------------------:|:-------------------------:
<img width="800" alt="Home Page" src="https://github.com/paulshaun-kdtk/Budget-Assist/assets/12745474/e6fff050-ff6c-4836-b4ad-70eb6f15c0c4"> | <img width="800" alt="Home Page" src="https://github.com/paulshaun-kdtk/Budget-Assist/assets/12745474/e436d45d-2441-4614-9e98-02a0c36ab3ae"> | <img width="800" alt="Home Page" src="https://github.com/paulshaun-kdtk/Budget-Assist/assets/12745474/68811561-38a7-458a-bca2-ebe57e2d9118">


**Expected:**

![image](https://github.com/paulshaun-kdtk/Budget-Assist/assets/12745474/c1d6fc0a-7623-4146-8386-e997eb4ed10f)

2023-12-23 23:08 UTC, Munsa1 requested changes
Hi @paulshaun-kdtk, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-12-23 23:08 UTC, Munsa1 commented on app/views/users/index.html.erb
> +                <th scope="col">total Amount</th>
- [ ] Great job making the requested changes, hwever an error has been introduced hindering the user from accessing the app. Kindly fix this.
![image](https://github.com/paulshaun-kdtk/Budget-Assist/assets/81932478/66543f8f-eef4-413a-b1c5-e54cf74d8c5b)

Videocast
[cinnamon-2023-12-24T010152+0200.webm](https://github.com/paulshaun-kdtk/Budget-Assist/assets/81932478/62861734-8b4d-40a0-9297-b15d0cec043b)

2024-01-08 08:03 UTC, closed without merging